# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171018_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='send_type',
        ),
        migrations.AlterField(
            model_name='deptprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='增加时间'),
        ),
        migrations.AlterField(
            model_name='deptprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
    ]
